export const INIT_MENU_ITEMS = 'INIT_MENU_ITEMS';
export const PHOTO_VIEWER_OPEN = 'PHOTO_VIEWER_OPEN';
export const PREV_IMAGE = 'PREV_IMAGE';
export const NEXT_IMAGE = 'NEXT_IMAGE';

export const FETCH_HEADER_IMAGES_BEGIN = 'FETCH_HEADER_IMAGES_BEGIN';
export const FETCH_HEADER_IMAGES_SUCCESS = 'FETCH_HEADER_IMAGES_SUCCESS';
export const FETCH_HEADER_IMAGES_FAILURE = 'FETCH_HEADER_IMAGES_FAILURE';
export const FETCH_SECTION_1_BEGIN = 'FETCH_SECTION_1_BEGIN';
export const FETCH_SECTION_1_SUCCESS = 'FETCH_SECTION_1_SUCCESS';
export const FETCH_SECTION_1_FAILURE = 'FETCH_SECTION_1_FAILURE';
export const FETCH_PICTURE_BOARD_BEGIN = 'FETCH_PICTURE_BOARD_BEGIN';
export const FETCH_PICTURE_BOARD_SUCCESS = 'FETCH_PICTURE_BOARD_SUCCESS';
export const FETCH_PICTURE_BOARD_FAILURE = 'FETCH_PICTURE_BOARD_FAILURE';
export const FETCH_OUR_PROCESS_DATA_BEGIN = 'FETCH_OUR_PROCESS_DATA_BEGIN';
export const FETCH_OUR_PROCESS_DATA_SUCCESS = 'FETCH_OUR_PROCESS_DATA_SUCCESS';
export const FETCH_OUR_PROCESS_DATA_FAILURE = 'FETCH_OUR_PROCESS_DATA_FAILURE';
