export const INIT_MENU_ITEMS = 'INIT_MENU_ITEMS';
export const FETCH_HEADER_IMAGES_BEGIN = 'FETCH_HEADER_IMAGES_BEGIN';
export const FETCH_HEADER_IMAGES_SUCCESS = 'FETCH_HEADER_IMAGES_SUCCESS';
export const FETCH_HEADER_IMAGES_FAILURE = 'FETCH_HEADER_IMAGES_FAILURE';
export const FETCH_SECTION_1_BEGIN = 'FETCH_SECTION_1_BEGIN';
export const FETCH_SECTION_1_SUCCESS = 'FETCH_SECTION_1_SUCCESS';
export const FETCH_SECTION_1_FAILURE = 'FETCH_SECTION_1_FAILURE';
